### PR TITLE
Add Organizers section

### LINKED ISSUE #2: Organizers section
Could you add a section that mentions the organizers?

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
- Change <a name> in _includes/partners.html
- Add <a name> to _includes/team.html
- Modify _config.yml to reflect above changes and link to team.html
- Add placeholder team members to _data/team.yml
- Add team.html section to index.html
- Modify social-media icon size so they're larger for team.html
- Closes #2

Signed-off-by: Achintya Rao <achintya.rao@cern.ch>

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
~~**TODO** for @JapanSciCom team: You will need to add images for the team members to `img/people` -- note the filenames here should reflect the filenames in `_data/team.yml`.~~

~~@neuroamanda: I know you wanted the team to appear below the "registration" block, but this conflicts stylistically with the top menu, where "registration" is the last element and also appears only after one has scrolled below the introductory block. Adding "team" below "registration" would involve incorrect movement (up and down) when navigating from the top menu.~~

If you want to make any changes:

- Add team members to `_data/team.yml` based on existing pattern (comment out the placeholder team member by deleting the `#` symbols).
- Move position of `{% include team.html %}` in index.html if you want.
    - Make sure to change the order in _config.yml if you move it above any of the other elements on the page.
- Change the value for `teamBlockTitle` in _config.yml if you want to rename the header for the team section.

**Comment by RaoOfPhysics** [comment]
This is what it looks line now:

iterm2 - - screen shot 19 feb 2018 at 14 50 28

This is what it will look like if you add any more "social media" accounts for the team members:

firefox - - screen shot 19 feb 2018 at 14 51 03

**Comment by neuroamanda** [comment]
@RaoOfPhysics : thanks.
* Just Twitter handles are sufficient
* Full names, Ayumi first. And affiliations (NIHU, RIKEN)
* Organizing team --> Organizers, to be consistent with menu
* What do you think, move Contact w/ email link to this section rather than have it kind of lost and obscure in the footer?

**Comment by RaoOfPhysics** [comment]
@neuroamanda: Added all organisers and changed header per your request.

I think you should leave contacts where it is as it's hard-coded to the footer and I don't want to mess with that as well.

**Pull request merged**
